/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TIANMA_TM040YDH65_ILI9806C_WVGA_VIDEO_H_

#define _PANEL_TIANMA_TM040YDH65_ILI9806C_WVGA_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config tianma_tm040ydh65_ili9806c_wvga_video_panel_data = {
  "qcom,mdss_dsi_tianma_tm040ydh65_ili9806c_wvga_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution tianma_tm040ydh65_ili9806c_wvga_video_panel_res = {
  480, 854, 100, 100, 10, 0, 20, 16, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info tianma_tm040ydh65_ili9806c_wvga_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd0[] = {
0x04, 0x00, 0x39, 0xC0,
0xFF, 0xFF, 0x98, 0x16,
 };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd1[] = {
0xBA, 0x60, 0x15, 0x80, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd2[] = {
0xB0, 0x01, 0x15, 0x80, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd3[] = {
0x13, 0x00, 0x39, 0xC0,
0xBC, 0x03, 0x0D, 0x03,
0x63, 0x01, 0x01, 0x1b,
0x11, 0x6e, 0x00, 0x00,
0x00, 0x01, 0x01, 0x16,
0x00, 0xff, 0xf2, 0xff  };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd4[] = {
0x09, 0x00, 0x39, 0xC0,
0xBD, 0x02, 0x13, 0x45,
0x67, 0x45, 0x67, 0x01,
0x23, 0xff, 0xff, 0xff  };



static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd5[] = {
0x12, 0x00, 0x39, 0xC0,
0xBE, 0x03, 0x22, 0x22,
0x22, 0x22, 0xDD, 0xCC,
0xBB, 0xAA, 0x66, 0x77,
0x22, 0x22, 0x22, 0x22,
0x22, 0x22, 0xFF, 0xFF,  };
				
static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd6[] = {
0x03, 0x00, 0x39, 0xC0,
0xED, 0x7F, 0x0F, 0xFF, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd7[] = {
0xF3, 0x70, 0x15, 0x80, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd8[] = {
0xB4, 0x02, 0x15, 0x80, };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd9[] = {
0x04, 0x00, 0x39, 0xC0,
0xC0, 0x0F, 0x0B, 0x0A, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd10[] = {
0x05, 0x00, 0x39, 0xC0,
0xC1, 0x17, 0x88, 0x70,
0x20, 0xFF, 0xFF, 0xFF, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd11[] = {
0xD8, 0x50, 0x15, 0x80, };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd12[] = {
0xFC, 0x07, 0x15, 0x80, };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd13[] = {
0x11, 0x00, 0x39, 0xC0,
0xE0, 0x00, 0x04, 0x12,
0x11, 0x13, 0x1e, 0Xc8,
0x08, 0x02, 0x09, 0x03,
0x0C, 0x0C, 0x2D, 0x2A,
0x00, 0xFF, 0xFF, 0xFF, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd14[] = {
0x11, 0x00, 0x39, 0xC0,
0xe1, 0x00, 0x02, 0x07,
0x0d, 0x11, 0x16, 0x7a,
0x09, 0x05, 0x09, 0x06,
0x0c, 0x0b, 0x2f, 0x2a,
0x00, 0xff, 0xff, 0xff,  };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd15[] = {
0x09, 0x00, 0x39, 0xC0,
0xd5, 0x0d, 0x08, 0x08,
0x09, 0xcb, 0xa5, 0x01,
0x04, 0xff, 0xff, 0xff,  };


#if 0
static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd151[] = {
0x05, 0x00, 0x39, 0xC0,
0xb5, 0x12, 0x14, 0x04,
0x00, 0xff, 0xff, 0xff,  };
#endif

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd16[] = {
0xf7, 0x89, 0x15, 0x80, };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd17[] = {
0xc7, 0x7f, 0x15, 0x80, };

static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd18[] = {
0x11, 0x00, 0x05, 0x80 };


static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd19[] = {
0x29, 0x00, 0x05, 0x80 };
#if 0
static char tianma_tm040ydh65_ili9806c_wvga_video_on_cmd20[] = {
0x36, 0x08, 0x15, 0x80 };
#endif
static struct mipi_dsi_cmd tianma_tm040ydh65_ili9806c_wvga_video_on_command[] = {
{ 0x8 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd0},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd1},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd2},
{ 0x18 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd3},
{ 0x10 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd4},
{ 0x18 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd5},
{ 0x8 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd6},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd7},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd8},
{ 0x08 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd9},
{ 0x0c , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd10},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd11},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd12},
{ 0x18 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd13},
{ 0x18 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd14},
{ 0x10 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd15},
//{ 0x0c,  tianma_tm040ydh65_ili9806c_wvga_video_on_cmd151},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd16},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd17},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd18,78},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_video_on_cmd19,32},
//{ 0x4,  tianma_tm040ydh65_ili9806c_wvga_video_on_cmd20,}
};
#define TIANMA_TM040YDH65_ILI9806C_WVGA_VIDEO_ON_COMMAND 20


static char tianma_tm040ydh65_ili9806c_wvga_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char tianma_tm040ydh65_ili9806c_wvga_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd tianma_tm040ydh65_ili9806c_wvga_video_off_command[] = {
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_videooff_cmd0},
{ 0x4 , tianma_tm040ydh65_ili9806c_wvga_videooff_cmd1}
};
#define TIANMA_TM040YDH65_ILI9806C_WVGA_VIDEO_OFF_COMMAND 2


static struct command_state tianma_tm040ydh65_ili9806c_wvga_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info tianma_tm040ydh65_ili9806c_wvga_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info tianma_tm040ydh65_ili9806c_wvga_video_video_panel = {
  1, 0, 0, 0, 1, 1, 0, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration tianma_tm040ydh65_ili9806c_wvga_video_lane_config = {
  2, 1, 1, 1, 0, 0
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t tianma_tm040ydh65_ili9806c_wvga_video_timings[] = {
  0x8d, 0x24, 0x19, 0x00, 0x34, 0x34, 0x1d, 0x26, 0x2a, 0x03, 0x04, 0x00
};

static struct panel_timing tianma_tm040ydh65_ili9806c_wvga_video_timing_info = {
  0, 4, 0x1f, 0x2d
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence tianma_tm040ydh65_ili9806c_wvga_video_reset_seq = {
        {2, 0, 2, }, {20, 20, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight tianma_tm040ydh65_ili9806c_wvga_video_backlight = {
  0, 1, 255, 0, 1, 0
};


#endif /*_PANEL_TIANMA_TM040YDH65_ILI9806C_WVGA_VIDEO_H_*/
